# Define the background function (no change from before)
def rtde_publisher_loop():
    while (True):
        write_output_float_register(0, 0.0)
        write_output_float_register(6, 0.0)
        write_output_float_register(18, 0.0)
        sleep(0.001)
    end
end

# Define a main function to start the thread
def rtde_publisher_main():
    # Run the continuous loop as a separate thread.
    run rtde_publisher_loop()
end